openapi: 3.0.0
info:
  title: Industry 5.0 Platform API
  version: '1.0'
  description: API for industrial IoT platform monitoring and management

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
          enum: [error]
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            details:
              type: object

    Machine:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum: [running, idle, maintenance]
        energyConsumption:
          type: number
        performanceData:
          type: object
          properties:
            cycleTime:
              type: number
            downtime:
              type: number
            throughput:
              type: number

paths:
  /auth/login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

  /machines/{machineId}/energy:
    get:
      security:
        - bearerAuth: []
      parameters:
        - name: machineId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Energy consumption data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Machine'

  /reports/productivity:
    get:
      security:
        - bearerAuth: []
      parameters:
        - name: siteId
          in: query
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Productivity report